# Generated by Django 3.1.6 on 2021-02-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('SecondName', models.CharField(max_length=30)),
                ('Surname', models.CharField(max_length=30)),
                ('Class', models.IntegerField(default=0)),
                ('Stream', models.CharField(max_length=30)),
                ('Dob', models.DateField()),
                ('ParentName', models.CharField(max_length=30)),
                ('ParentContact', models.CharField(max_length=30)),
                ('EmergencyContact', models.CharField(max_length=30)),
                ('ParentEmail', models.EmailField(max_length=30)),
                ('HomeCounty', models.CharField(max_length=30)),
                ('District', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('DoA', models.DateField(auto_now_add=True)),
                ('Kcpe', models.IntegerField(default=0)),
                ('Dormitory', models.CharField(max_length=30)),
                ('Clubs', models.CharField(max_length=30)),
                ('Others', models.TextField(max_length=30)),
                ('Passport', models.ImageField(upload_to='StudentImages')),
                ('Status', models.IntegerField(default=1)),
                ('_createdAt', models.DateField(auto_now_add=True)),
                ('_updatedAt', models.DateField(auto_now=True)),
                ('_updatedBy', models.CharField(max_length=30)),
            ],
        ),
    ]
