# Generated by Django 3.1.6 on 2021-02-13 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=2)),
                ('Status', models.IntegerField(max_length=2)),
                ('ClassNumber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Student.student')),
            ],
        ),
    ]
