# Generated by Django 3.1.6 on 2021-02-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_studentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
