# Generated by Django 3.1.6 on 2021-02-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20210215_0950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
