# Generated by Django 3.1.6 on 2021-02-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=20)),
                ('Status', models.IntegerField()),
                ('_createdAt', models.DateField(auto_now_add=True)),
                ('_updatedAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
